
version: "3.1"

services:
  db:
    image: postgres
    container_name: airline-tickets-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airlinedb
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/InitialDatabase.sql:/docker-entrypoint-initdb.d/InitialDatabase.sql

volumes:
  pgdata: